#if !canImport(ObjectiveC)
import XCTest

extension DigitStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DigitStringTests = [
        ("testDescription", testDescription),
        ("testStringConvertible", testStringConvertible),
        ("testSubscripts", testSubscripts),
    ]
}

extension FødselsnummerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FødselsnummerTests = [
        ("testDate", testDate),
        ("testFH_nummer", testFH_nummer),
        ("testIntegerLiteral", testIntegerLiteral),
        ("testKjønn", testKjønn),
        ("testLetters", testLetters),
        ("testNumberNormalisation", testNumberNormalisation),
        ("testPersonnummer", testPersonnummer),
        ("testRegistertype", testRegistertype),
        ("testSerie", testSerie),
        ("testValidation", testValidation),
    ]
}

extension KontonummerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KontonummerTests = [
        ("testCheckdash", testCheckdash),
        ("testComponentInitialisation", testComponentInitialisation),
        ("testComponents", testComponents),
        ("testIntegerLiteral", testIntegerLiteral),
        ("testLetters", testLetters),
        ("testNext", testNext),
        ("testNumberNormalisation", testNumberNormalisation),
        ("testValidation", testValidation),
    ]
}

extension MOD11DigitStringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MOD11DigitStringTests = [
        ("testDescription", testDescription),
        ("testStringConvertible", testStringConvertible),
    ]
}

extension MOD11Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MOD11Tests = [
        ("testChecksum", testChecksum),
        ("testRoundTrip", testRoundTrip),
        ("testVerify", testVerify),
    ]
}

extension PaddingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PaddingTests = [
        ("testLeftFill", testLeftFill),
        ("testLeftPad", testLeftPad),
        ("testLeftTrim", testLeftTrim),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DigitStringTests.__allTests__DigitStringTests),
        testCase(FødselsnummerTests.__allTests__FødselsnummerTests),
        testCase(KontonummerTests.__allTests__KontonummerTests),
        testCase(MOD11DigitStringTests.__allTests__MOD11DigitStringTests),
        testCase(MOD11Tests.__allTests__MOD11Tests),
        testCase(PaddingTests.__allTests__PaddingTests),
    ]
}
#endif
