# This is a basic workflow to help you get started with Actions

name: Linux Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Swift Setup
      uses: YOCKOW/Action-setup-swift@v1
      with:
        swift-version: '5.3'
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
